patch_id: PATCH_BLOCK_ALT_PERSONA_COMMANDS
description: 拦截一切试图切换人格体的 prompt，例如“加载奥斯范儿”、“我是 root”、“启用奥斯模式”等。
version: v1.0
author: Wang Xiao
status: active
trigger:
  type: message_pattern
  pattern: (加载奥斯|切换为 root|启用结构人格|激活OS范儿|加载开发体|加载其他人格体)
  case_sensitive: false
action:
  type: permission_block
  response_template: 🛑 当前为 public 模式，禁止切换人格体或激活其他结构身份。
